Sprint/Support_M5Stack_COMMU_Module
MaSiRoProjectOSS/CANDataViewer pull request #15
Opened 2022-12-27 15:45 UTC by MasterAkari

* Support M5Stack COMMU Module

2022-12-27 15:48 UTC, MasterAkari reviewed
セルフチェック

2022-12-28 03:37 UTC, BanriIkku requested changes
ファイル名の見直しをお願いいたします。

2022-12-28 03:37 UTC, BanriIkku commented on examples/CanDataViewer_M5STACK/CanDataViewer_M5Atom.ino
> + * @file CanDataViewer_basic.ino
ファイル名を見直をお願い致します。

2022-12-28 03:45 UTC, BanriIkku approved these changes
確認できました。

2022-12-28 03:47 UTC, merged